color: null
description: null
fieldLayouts:
  ea01f473-641e-4328-9d70-9bd046887751:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-11-06T07:52:37+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: a80b5d3b-65b8-46af-b0da-0142b33116ea
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-11-06T07:56:19+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: ae20a0eb-ca79-4174-a108-fa84b7746120 # Link
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c8d481e6-0149-4a46-b952-16830d6b19ca
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-11-06T07:56:19+00:00'
            editCondition: null
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\fields\conditions\LinkFieldConditionRule
                  fieldUid: ae20a0eb-ca79-4174-a108-fa84b7746120 # Link
                  layoutElementUid: c8d481e6-0149-4a46-b952-16830d6b19ca
                  linkType: url
                  operator: type
                  uid: 097ea39f-ec2a-4c85-a23c-45cd9b5b319e
                  value: ''
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: 196d1915-312c-47ea-b919-c544966f0d2b # Icoon
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7ec58748-ed49-44ca-b82d-8682eca07af6
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: c31f5d84-4502-44eb-8051-7936fb3056fb
        userCondition: null
handle: externalLink
hasTitleField: true
icon: null
name: 'Externe link'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
