altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  6f0b2ae6-8976-4f41-94a4-a9506f4c924c:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-11-06T09:35:31+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 52234685-9270-41e7-930c-79f92bf358dc
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 7f7b79b6-3055-4413-86fe-8144ee0da3f1
        userCondition: null
fs: logos
handle: logos
name: Logos
sortOrder: 2
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
