columnSuffix: null
handle: navIcon
instructions: null
name: Icoon
searchable: false
settings:
  fullGraphqlData: true
  includeProIcons: false
translationKeyFormat: null
translationMethod: none
type: craft\fields\Icon
