dateModified: 1762500473
elementSources:
  craft\elements\Asset:
    -
      defaultSort:
        - dateCreated
        - desc
      defaultViewMode: ''
      disabled: false
      key: 'volume:6d83ddd1-f2ce-4ce6-9aac-88fcbf50c2d8' # Foto's
      tableAttributes:
        - filename
        - 'field:9ccfab1b-7fcd-4e50-9b17-9cd30330a654' # Categorie
        - size
        - dateModified
        - link
      type: native
    -
      key: temp
      type: native
  craft\elements\Entry:
    -
      key: '*'
      type: native
    -
      defaultSort:
        - title
        - asc
      defaultViewMode: ''
      disabled: false
      key: singles
      tableAttributes:
        - status
        - link
        - type
      type: native
    -
      heading: Structures
      key: 'heading:66843399-a155-4113-8ec7-d77366cd1518'
      type: heading
    -
      key: 'section:2ccfb376-804c-4417-836c-b2a543c2d25f' # Categorieën
      type: native
    -
      key: 'section:34d01be4-5471-43d6-ad9e-886596d50f55' # Navigatie
      type: native
    -
      key: 'section:f85234e0-dbb8-4870-a766-db020921bd9f' # Klanten
      type: native
    -
      defaultSort:
        - structure
        - asc
      defaultViewMode: ''
      disabled: false
      key: 'section:76bff2af-8e60-4d73-9346-76389dbe69f0' # Pagina's
      tableAttributes:
        - status
        - postDate
        - expiryDate
        - link
      type: native
    -
      heading: ''
      key: 'heading:d4e4b89f-3fe1-4fb2-ad41-8c481d80b3ad'
      type: heading
email:
  fromEmail: admin@janhendrickx.be
  fromName: 'The Annie Club'
  transportType: craft\mail\transportadapters\Sendmail
fs:
  bestanden:
    hasUrls: true
    name: Bestanden
    settings:
      path: '@webroot/uploads/fotos'
    type: craft\fs\Local
    url: '@web/uploads/fotos'
  logos:
    hasUrls: true
    name: Logos
    settings:
      path: '@webroot/uploads/logos'
    type: craft\fs\Local
    url: '@web/uploads/logos'
graphql:
  publicToken:
    enabled: false
    expiryDate: null
meta:
  __names__:
    0e0c46fb-9378-4e66-93e1-b773b3831507: Simple # Simple
    1f427c2e-086a-4959-9c27-28358a0abeef: Logo # Logo
    2ccfb376-804c-4417-836c-b2a543c2d25f: Categorieën # Categorieën
    5fc80e32-db57-4dfa-9d7f-a22ae92ca168: 'Te tonen categorieën' # Te tonen categorieën
    6ce5706b-7cce-45e2-b3d7-ebbf369ed760: Fotogalerij # Fotogalerij
    6d83ddd1-f2ce-4ce6-9aac-88fcbf50c2d8: "Foto's" # Foto's
    7c714788-dbde-4f28-9034-28adbf9cf5da: Fotogallery # Fotogallery
    8f0771fb-3769-4c03-9c9b-b7cc756d9140: Klant # Klant
    9ccfab1b-7fcd-4e50-9b17-9cd30330a654: Categorie # Categorie
    34d01be4-5471-43d6-ad9e-886596d50f55: Navigatie # Navigatie
    76bff2af-8e60-4d73-9346-76389dbe69f0: "Pagina's" # Pagina's
    86ce5424-7b9d-4d8e-ad8b-02756a48a9de: Website # Website
    96da3f18-1b13-4c2c-8aff-47ceb2649faa: Pagina # Pagina
    196d1915-312c-47ea-b919-c544966f0d2b: Icoon # Icoon
    460ec1d4-502a-4553-82f2-23c3f41054a7: Home # Home
    702fb49c-145b-4804-9326-248b64c7d98c: 'The Annie Club' # The Annie Club
    940ab21b-abee-4658-9c5c-a914247d6f28: "Foto's" # Foto's
    1560e09b-7782-4fc6-8b2e-c0bdd137dcf9: Logos # Logos
    5724cdab-a194-4976-b0a9-cfdb42b12b60: Tekst # Tekst
    9137badf-6673-4593-9592-2e59855c1988: Fotos # Fotos
    5670040b-eaf9-43e6-91bf-337086235699: Fotos # Fotos
    96232019-438e-4cf2-9ec3-363faddbc88b: Pagina # Pagina
    a074cdd3-6fd9-4044-b0cc-f65f5af6a9f3: Klanten # Klanten
    ae20a0eb-ca79-4174-a108-fa84b7746120: Link # Link
    b2a8d6cc-0b1f-4039-842f-2977ac14c237: Link # Link
    b7f3fc25-f9a6-45b0-ae16-e3f5eaee24b4: Homepage # Homepage
    bfc312f2-32f3-405b-939b-be57886d68b4: 'Externe link' # Externe link
    dd6e4919-ff41-4207-af9c-630665454e96: 'The Annie Club' # The Annie Club
    e5999d1c-04e2-4d0e-ba9c-abdaf5aabf2e: Categorie # Categorie
    eefc48d9-7057-4082-af4f-617e5053f422: Contactpagina # Contactpagina
    f85234e0-dbb8-4870-a766-db020921bd9f: Klanten # Klanten
plugins:
  ckeditor:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0.0
system:
  edition: solo
  live: true
  name: 'The Annie Club'
  retryDuration: null
  schemaVersion: 5.8.0.3
  timeZone: Europe/Brussels
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
