defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 96da3f18-1b13-4c2c-8aff-47ceb2649faa # Pagina
handle: clientsOverview
maxAuthors: 1
name: Klanten
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  dd6e4919-ff41-4207-af9c-630665454e96: # The Annie Club
    enabledByDefault: true
    hasUrls: true
    template: clients.twig
    uriFormat: klanten
type: single
