defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 96da3f18-1b13-4c2c-8aff-47ceb2649faa # Pagina
  -
    uid: eefc48d9-7057-4082-af4f-617e5053f422 # Contactpagina
handle: paginas
maxAuthors: 1
name: "Pagina's"
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  dd6e4919-ff41-4207-af9c-630665454e96: # The Annie Club
    enabledByDefault: true
    hasUrls: true
    template: page
    uriFormat: '{slug}'
structure:
  maxLevels: null
  uid: 76c5ea50-3687-4251-b15c-84b8fc0ad08c
type: structure
